version: "3"

services:
    web:
        build: .
        image: edcon:v1.0
        container_name: edcon
        restart: always
        env_file:
            - .env
        command: python manage.py runserver --insecure 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
volumes:
    .:
